### ISSUE TITLE
Xcode Cloud

### ISSUE THREAD

**Issue by zach-withcoherence** [ml-explore/mlx-swift-examples#143]
I've got an app where I've made this repo a Package Dependency in Xcode. The app builds and runs great, and I can distribute to TestFlight from my workstation. However, on Xcode Cloud I am getting the error "PrepareMetalShaders is disabled". I have tried adding this as a Build Tool Plugin but the package does not support running that way. Has anyone faced a similar issue? Thanks!

**Comment by davidkoski** [comment]
I don't have experience with it, but:

- https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305/6

suggests:

1. you can't use plugins with Xcode cloud
2. there is a workaround

We already have a script that packages up the JIT enabled shaders:

- https://github.com/ml-explore/mlx-swift/blob/main/tools/update-mlx.sh

We could potentially use something like that instead of the plugin -- all it is doing is copying files around and adjusting the paths in the `#include`.

**Comment by zach-withcoherence** [comment]
Thank you for the response. I was able to get it working using the workaround mentioned in that forum post, in case that is helpful for anyone else. Can close this issue but probably worth looking at if there is a cleaner solution here. Appreciated!

**Comment by davidkoski** [comment]
Added #144 to remove this in the future
